name: Run Bash Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_bash_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Disables default credentials to use a custom token

      - name: Set up Python Environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Download Chrome Headless Shell
        run: |
          wget -O chrome-headless-shell-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.91/linux64/chrome-headless-shell-linux64.zip
          unzip chrome-headless-shell-linux64.zip -d ./chrome_headless_shell

      - name: Commit and Push Downloaded File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add chrome-headless-shell-linux64.zip
          git commit -m "Add downloaded Chrome Headless Shell file"
          git push
