name: Run Bash Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_bash_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python Environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Download Chrome Headless Shell
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.91/linux64/chrome-headless-shell-linux64.zip
          unzip chrome-headless-shell-linux64.zip -d /usr/local/bin/
